import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://10.43.6.180:55209/magenta/login');
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('pg1');
  await page.getByRole('textbox', { name: 'User ID' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('bcabca');
  await page.getByRole('button', { name: 'LOGIN' }).click();
  await page.locator('a').filter({ hasText: 'Pengajuan Merchant' }).nth(1).click();
  await page.locator('a').filter({ hasText: 'Pengajuan Bulk' }).first().click();
  await page.locator('a').filter({ hasText: 'Pengajuan Merchant' }).nth(1).click();
  await page.locator('iframe').contentFrame().getByRole('link', { name: ' Daftar Sebagai Rekening Non' }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Nama Pemilik' }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Nama Pemilik' }).fill('Tesing 1');
  await page.locator('iframe').contentFrame().locator('#ember574 i').click();
  await page.locator('iframe').contentFrame().locator('#ember846 i').click();
  await page.locator('iframe').contentFrame().getByText('Bukan Nasabah BCA').click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'No. Rekening' }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'No. Rekening' }).fill('1111');
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Nama Bank' }).click();
  await page.locator('iframe').contentFrame().locator('#ember481').click();
  await page.locator('iframe').contentFrame().locator('#ember481').fill('');
  await page.locator('iframe').contentFrame().locator('#ember484').click();
  await page.locator('iframe').contentFrame().locator('#ember484').fill('BCA');
  await page.locator('iframe').contentFrame().getByRole('cell', { name: 'BCA ' }).locator('i').click();
  await page.locator('iframe').contentFrame().getByRole('cell', { name: '0140004' }).click();
  await page.locator('iframe').contentFrame().getByRole('cell', { name: 'BCA', exact: true }).first().click();
  await page.locator('iframe').contentFrame().getByRole('button', { name: '×' }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Total Lembar Saham' }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Nama Pejabat 1' }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Nama Pejabat 1' }).fill('MNB');
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'KTP Pejabat 1' }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'KTP Pejabat 1' }).fill('1231');
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Paspor Pejabat 1' }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Paspor Pejabat 1' }).fill('233');
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Jabatan Pejabat 1' }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Jabatan Pejabat 1' }).fill('seddaw');
  await page.locator('iframe').contentFrame().locator('#ember889 i').click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Jumlah Lembar Saham Pejabat 1' }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Nama Pejabat 2' }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Nama Pejabat 2' }).fill('sssd');
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'KTP Pejabat 2' }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'KTP Pejabat 2' }).fill('99301341');
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Paspor Pejabat 2' }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Paspor Pejabat 2' }).fill('22343');
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Jabatan Pejabat 2' }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Jabatan Pejabat 2' }).fill('dsdfsg');
  await page.locator('iframe').contentFrame().locator('#ember909 i').click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Jumlah Lembar Saham Pejabat 2' }).click();
  await page.locator('iframe').contentFrame().locator('#ember949 label').click();
  await page.locator('iframe').contentFrame().getByRole('radio', { name: ' Ya' }).press('d');
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Penerima Kuasa' }).click();
  await page.locator('iframe').contentFrame().getByRole('radio', { name: ' Ya' }).press('f');
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Penerima Kuasa' }).fill('esfef');
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'KTP/ KITAS / KITAP' }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'KTP/ KITAS / KITAP' }).fill('23e3224');
  await page.locator('iframe').contentFrame().getByText('Pengajuan Dikuasakan Ya Tidak Penerima Kuasa KTP / KITAS / KITAP Paspor').click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Paspor', exact: true }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Paspor', exact: true }).fill('fsrfrsfrfsr');
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'HP', exact: true }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'HP', exact: true }).fill('23');
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'HP', exact: true }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'HP', exact: true }).fill('23422323');
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Telepon / HP' }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'HP', exact: true }).fill('234223234');
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Telepon / HP' }).fill('22342423');
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Contoh: melisa@bca.co.id,' }).click();
  await page.locator('iframe').contentFrame().getByRole('textbox', { name: 'Contoh: melisa@bca.co.id,' }).fill('sdkefj');
});